services:
  app:
    build: .
    ports:
      - "8090:9013"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Datasource config is now in application-dev.yml


  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ttcc1234
      MARIADB_DATABASE: db_nanum
    ports:
      - "33306:3306"


    volumes:
      - ./Local/DB:/var/lib/mysql

