server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    # Production Settings (ToDo: Change IP/Auth)
    url: jdbc:mariadb://localhost:3306/db_nanum?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ttcc1234
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.nanum.domain.**.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.nanum: WARN

file:
  storage:
    type: local
    server-domain: http://localhost:8080
    local:
      path: ${CONTAINER_UPLOAD_PATH:/app/uploads/} # Default to /app/uploads/ if env var not set
