server:
  port: 8090
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  datasource:
    # Remote Dev DB Connect
    url: jdbc:mariadb://58.225.62.238:33306/db_nanum?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ttcc1234
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ctso.domain.**.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.ctso: DEBUG

file:
  storage:
    type: local
    server-domain: http://localhost:8090
    local:
      path: ${CONTAINER_UPLOAD_PATH:./uploads/}
