-- -----------------------------------------------------
-- Claim (Order Claim)
-- -----------------------------------------------------
CREATE TABLE claim (
    claim_id         INT AUTO_INCREMENT COMMENT '클레임ID',
    site_cd          VARCHAR(100) NULL COMMENT '사이트코드',
    member_code      VARCHAR(30) NOT NULL COMMENT '회원코드',
    claim_cd         VARCHAR(10) NOT NULL COMMENT '클레임코드',
    order_id         INT NOT NULL COMMENT '주문ID',
    order_seq        INT NULL COMMENT '주문순번',
    claim_type       VARCHAR(10) NOT NULL COMMENT '클레임타입',
    claim_gubun      VARCHAR(10) NULL COMMENT '클레임구분',
    claim_reason     TEXT NULL COMMENT '클레임사유',
    claim_status     VARCHAR(20) NOT NULL COMMENT '클레임상태',
    claim_date_entry DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '클레임신청일시',
    claim_check      VARCHAR(10) NULL COMMENT '확인여부',
    claim_date_check DATETIME NULL COMMENT '확인일시',
    claim_check_cd   VARCHAR(30) NULL COMMENT '확인자(ManagerCode)',
    claim_memo       TEXT NULL COMMENT '관리자메모',
    vbank_input_name VARCHAR(40) NULL COMMENT '가상계좌 입금자명',
    vbank_bank_name  VARCHAR(40) NULL COMMENT '가상계좌 은행명',
    vbank_num        VARCHAR(40) NULL COMMENT '가상계좌번호',
    refund_type      VARCHAR(20) NULL COMMENT '환불타입',
    return_zipcode   VARCHAR(10) NULL COMMENT '반품우편번호',
    return_address   VARCHAR(200) NULL COMMENT '반품주소',
    return_detail    VARCHAR(200) NULL COMMENT '반품상세주소',
    refund_check     VARCHAR(10) NULL COMMENT '환불확인',
    refund_price     DECIMAL(19, 4) NULL COMMENT '환불금액',
    claim_cnt        INT NULL COMMENT '클레임횟수',
    product_id       INT NULL COMMENT '상품ID',
    option_id        INT NULL COMMENT '옵션ID',
    exchange_zipcode VARCHAR(10) NULL COMMENT '교환우편번호',
    exchange_address VARCHAR(200) NULL COMMENT '교환주소',
    exchange_detail  VARCHAR(200) NULL COMMENT '교환상세주소',
    refund_status    VARCHAR(20) NULL COMMENT '환불상태',
    refund_manager_cd VARCHAR(30) NULL COMMENT '환불담당자(ManagerCode)',
    reg_by           VARCHAR(30) NULL COMMENT '등록자(MemberCode)',
    PRIMARY KEY (claim_id),
    CONSTRAINT fk_claim_member FOREIGN KEY (member_code) REFERENCES member (member_code) ON DELETE CASCADE,
    CONSTRAINT fk_claim_order FOREIGN KEY (order_id) REFERENCES order_master (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_claim_product FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE SET NULL
) COMMENT '주문 클레임';
