CREATE TABLE db_aleva.dbo.SHOP_DISCLOSURE_CODE (
	DC_KEY int NOT NULL,
	DC_CODE varchar(20) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	DC_NAME varchar(100) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	DC_VIEWYN varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NOT NULL,
	DC_USEYN varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NOT NULL,
	CONSTRAINT SHOP_DISCLOSURE_CODE_PK PRIMARY KEY (DC_KEY)
);

CREATE TABLE db_aleva.dbo.SHOP_DISCLOSURE_QUESTION (
	DQ_KEY int NOT NULL,
	DQ_NAME varchar(100) COLLATE Korean_Wansung_CI_AS NOT NULL,
	DQ_SORT int DEFAULT '1' NOT NULL,
	DQ_USEYN varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NOT NULL,
	DC_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	CONSTRAINT SHOP_DISCLOSURE_QUESTION_PK PRIMARY KEY (DQ_KEY)
);

CREATE TABLE db_aleva.dbo.SHOP_PRODUCT_DISCLOSURE (
	PD_KEY int IDENTITY(1,1) NOT NULL,
	PD_PDT_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PD_DC_CODE varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PD_DQ01_KEY int DEFAULT '0' NOT NULL,
	PD_DQ01_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ02_KEY int DEFAULT '0' NOT NULL,
	PD_DQ02_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ03_KEY int DEFAULT '0' NOT NULL,
	PD_DQ03_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ04_KEY int DEFAULT '0' NOT NULL,
	PD_DQ04_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ05_KEY int DEFAULT '0' NOT NULL,
	PD_DQ05_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ06_KEY int DEFAULT '0' NOT NULL,
	PD_DQ06_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ07_KEY int DEFAULT '0' NOT NULL,
	PD_DQ07_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ08_KEY int DEFAULT '0' NOT NULL,
	PD_DQ08_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ09_KEY int DEFAULT '0' NOT NULL,
	PD_DQ09_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ10_KEY int DEFAULT '0' NOT NULL,
	PD_DQ10_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ11_KEY int DEFAULT '0' NOT NULL,
	PD_DQ11_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ12_KEY int DEFAULT '0' NOT NULL,
	PD_DQ12_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ13_KEY int DEFAULT '0' NOT NULL,
	PD_DQ13_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	PD_DQ14_KEY int DEFAULT '0' NOT NULL,
	PD_DQ14_ANS varchar(MAX) COLLATE Korean_Wansung_CI_AS DEFAULT '' NOT NULL,
	CONSTRAINT SHOP_PRODUCT_DISCLOSURE_PK PRIMARY KEY (PD_KEY)
);