CREATE TABLE inout_master (
  io_seq 			INT(11) NOT NULL AUTO_INCREMENT COMMENT 'pk',
  io_code 			VARCHAR(45) NOT NULL COMMENT '입출고코드',
  io_type 			VARCHAR(10) NOT NULL COMMENT '입출고구분 IN: 입고, OUT: 출고',
  io_category 		VARCHAR(20) NOT NULL COMMENT '입출고 상세카테고리 (일반입고, 생산입고, 반품입고, 일반출고, 생산출고, 주문출고, 폐기출고)',
  io_date 			DATETIME DEFAULT NULL COMMENT '입고일',
  order_no 			VARCHAR(45) DEFAULT NULL COMMENT '주문번호',
  manager_code		VARCHAR(30) DEFAULT NULL COMMENT '관리자코드(MGR+6자리)',

  created_at 		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
  created_by 		VARCHAR(50) NULL COMMENT '생성자',
  updated_at 		DATETIME NULL COMMENT '수정일',
  updated_by 		VARCHAR(50) NULL COMMENT '수정자',
  deleted_at 		DATETIME NULL COMMENT '삭제일',
  deleted_by 		VARCHAR(50) NULL COMMENT '삭제자',
  delete_yn 		CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제유무',
  PRIMARY KEY (io_seq),
  UNIQUE KEY uq_inout_io_code (io_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='입출고 Master';


CREATE TABLE inout_detail (
  io_code 			VARCHAR(45) NOT NULL COMMENT '입출고코드 (IO+8자리)',
  no 				INT(11) NOT NULL COMMENT '번호',
  io_type 			VARCHAR(10) NOT NULL COMMENT '입출고구분 IN: 입고, OUT: 출고',
  in_io_code 		VARCHAR(45) DEFAULT NULL COMMENT '입고 코드',
  in_no	 	 		INT(11) DEFAULT NULL COMMENT '입고 코드의번호', 
  product_id 		INT(11) DEFAULT NULL COMMENT '상품ID',
  product_name 		VARCHAR(200) DEFAULT NULL COMMENT '상품명',
  option_id 		INT(11) DEFAULT NULL COMMENT '옵션ID',
  option_name 		VARCHAR(200) DEFAULT NULL COMMENT '옵션명',
  brand_name 		VARCHAR(100) DEFAULT NULL COMMENT '브랜드명',
  qty 				INT(11) DEFAULT '0' COMMENT '입출고수량',
  real_qty 			INT(11) DEFAULT '0' COMMENT '재고잔량',
  from_type 		CHAR(1) DEFAULT NULL COMMENT 'FROM (C:거래처, S:창고, L:라인)',
  location_type 	CHAR(1) DEFAULT NULL COMMENT 'TO (C:거래처, S:창고, L:라인)',
  to_type 			CHAR(1) DEFAULT NULL COMMENT 'TO (C:거래처, S:창고, L:라인)',
  location1 		INT(11) DEFAULT NULL COMMENT '위치1',
  location2 		INT(11) DEFAULT NULL COMMENT '위치2',
  location3 		INT(11) DEFAULT NULL COMMENT '위치3',
  from_location1 	INT(11) DEFAULT NULL COMMENT 'FROM 위치1',
  from_location2 	INT(11) DEFAULT NULL COMMENT 'FROM 위치2',
  from_location3 	INT(11) DEFAULT NULL COMMENT 'FROM 위치3',
  to_location1 		INT(11) DEFAULT NULL COMMENT 'TO 위치1',
  to_location2 		INT(11) DEFAULT NULL COMMENT 'TO 위치2',
  to_location3 		INT(11) DEFAULT NULL COMMENT 'TO 위치3',
  memo 				VARCHAR(200) DEFAULT NULL COMMENT '메모',

  created_at 		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
  created_by 		VARCHAR(50) NULL COMMENT '생성자',
  updated_at 		DATETIME NULL COMMENT '수정일',
  updated_by 		VARCHAR(50) NULL COMMENT '수정자',
  deleted_at 		DATETIME NULL COMMENT '삭제일',
  deleted_by 		VARCHAR(50) NULL COMMENT '삭제자',
  delete_yn 		CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제유무',
  PRIMARY KEY (io_code, no),
  CONSTRAINT fk_inout_detail_io_code FOREIGN KEY (io_code) REFERENCES inout_master (io_code) ON DELETE CASCADE,
  CONSTRAINT fk_inout_detail_product FOREIGN KEY (product_id) REFERENCES product (product_id),
  KEY idx_inout_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='입출고 Detail';