CREATE TABLE popup (
    popup_id       INT AUTO_INCREMENT COMMENT '팝업코드',
    site_cd        VARCHAR(20) DEFAULT 'SITECD000001' NULL COMMENT '사이트코드',
    title          VARCHAR(100) NOT NULL COMMENT '팝업제목',
    content_html   TEXT NULL COMMENT '팝업내용(HTML)',
    link_type      VARCHAR(20) NULL COMMENT '링크 타입',
    link_url       VARCHAR(255) NULL COMMENT '링크 URL',
    width          INT DEFAULT 400 NOT NULL COMMENT '창 너비',
    height         INT DEFAULT 500 NOT NULL COMMENT '창 높이',
    pos_x          INT DEFAULT 0 NOT NULL COMMENT '위치 X좌표',
    pos_y          INT DEFAULT 0 NOT NULL COMMENT '위치 Y좌표',
    close_type     VARCHAR(20) DEFAULT 'DAY' NOT NULL COMMENT '닫기옵션 (NEVER, DAY, ONCE)',
    device_type    VARCHAR(10) DEFAULT 'ALL' NOT NULL COMMENT '노출기기 (PC, MOBILE, ALL)',
    start_datetime DATETIME NOT NULL COMMENT '게시 시작일시',
    end_datetime   DATETIME NOT NULL COMMENT '게시 종료일시',
    use_yn         CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '사용유무',
    delete_yn      CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제유무',
    created_at     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
    created_by     INT NULL COMMENT '생성자',
    updated_at     DATETIME NULL COMMENT '수정일',
    updated_by     INT NULL COMMENT '수정자',
    deleted_at     DATETIME NULL COMMENT '삭제일',
    deleted_by     INT NULL COMMENT '삭제자',
    PRIMARY KEY (popup_id),
    INDEX idx_popup_date (start_datetime, end_datetime)
) COMMENT '팝업 관리';
